./main -ga -f ../Data/ND-web.edge
./main -ga -f ../Data/ND-web.edge
./main -ga -f ../Data/ND-web.edge
./main -ga -f ../Data/ND-web.edge
./main -ga -f ../Data/ND-web.edge
./main -ga -f ../Data/mithandor-0.0001.edge
./main -ga -f ../Data/mithandor-0.0001.edge
./main -ga -f ../Data/mithandor-0.0001.edge
./main -ga -f ../Data/mithandor-0.0001.edge
./main -ga -f ../Data/mithandor-0.0001.edge
